### ISSUE TITLE
Add wdth-* css

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew#4145]
@thomasgohard what are your thoughts in adding in .wdth-* classes?  They get uses a lot on tables to control how wide columns will be...cuz otherwise you just get the browser default and often that's not preferred.  The catch is that ideally we would what -xs, -sm, -md and -lg ones and they would cascade just like grids do.

Likely in multiples of 10.  So it would be
```css
.wdth-xs-10{width:10%}
.wdth-xs-20{width:20%}
....
.wdth-xs-90{width:90%}
.wdth-xs-100{width:100%}

.wdth-sm-10{width:10%}
.wdth-sm-20{width:20%}
....
.wdth-sm-90{width:90%}
.wdth-sm-100{width:100%}

.wdth-md-10{width:10%}
.wdth-md-20{width:20%}
....
.wdth-md-90{width:90%}
.wdth-md-100{width:100%}

.wdth-lg-10{width:10%}
.wdth-lg-20{width:20%}
....
.wdth-lg-90{width:90%}
.wdth-lg-100{width:100%}
```
