### ISSUE TITLE
Multimedia Player - YouTube: Bottom border

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#6224]
Why is there a 10px border to the bottom of the control box?

```CSS
.wb-mltmd.youtube .wb-mm-ctrls {
  border-bottom: 10px solid #FFFFFF;
}
```

It only seems to be only for the Youtube video.

If it's not needed I can remove it, just thought I'd ask first.

CC/ @laurentgoderre
