### ISSUE TITLE
WET 4 - Input type=file render in a less than ideal way in Firefox

### ISSUE THREAD

**Issue by chyne** [wet-boew/wet-boew#6245]
See attached image:
![input-type-file](https://cloud.githubusercontent.com/assets/245596/4937817/d245e13a-65c6-11e4-92b7-4a948c431399.png)

**Comment by cvrebert** [comment]
As alluded to by http://getbootstrap.com/css/#forms-example , `.form-control` is only meant for use on `<textarea>`, `<select>`, and textual `<input>`s.
`<input type="file">` doesn't fall under any of those categories.

**Comment by CalvinRodo** [comment]
That should be added to the WET documentation.

**Comment by hsrudnicki** [comment]
@LaurentGoderre @zachfalsetto @thomasgohard and others: Can be this issue closed?

**Comment by CalvinRodo** [comment]
@hsrudnicki I'm not seeing any mention of input[type="file"] in the documentation so no this cannot be closed.

**Comment by hsrudnicki** [comment]
@zachfalsetto and others: Has been the documentation updated as discussed?  Please update this issue's status whether this issue can be closed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue or otherwise? Either way, please update this issue's status, thank you

**Comment by CalvinRodo** [comment]
The documentation has not been updated so this needs to be reopened.

**Comment by hsrudnicki** [comment]
Based on the above, this is reopened, please keep this issue's status updated, thank you

**Comment by hsrudnicki** [comment]
In the above, there is a mention of input[type="file"] to be added into the documentation, see #5574

**Comment by hsrudnicki** [comment]
This has been referenced with the issue 5574 to be added into the docs,  so, can be this closed as resolved or otherwise?

**Comment by CalvinRodo** [comment]
Well you've referenced it, but closing this issue will show the referenced item as closed in that issue, that would imply to me that the work is done when it's not.

**Comment by hsrudnicki** [comment]
OK we are dealing with problematic dependency, therefore again, due to a strong and direct dependency between this and  the referenced issue, this issue remains open until this will be implemented in the referenced issue.

**Comment by cybersubtype** [comment]
@chyne @LaurentGoderre @CalvinRodo What about this...

HTML:
```html
<!-- For multiple file inputs -->
<label for="files" class="required"><span class="field-name">Files</span></label>
<div class="form-group form-sm">
	<input id="files" class="file-control file-control-1" name="files" type="file" data-multiple-caption="{count} files selected" data-rule-extension="pdf" multiple="multiple">
	<label for="files">
		<strong class="btn btn-md btn-default">Choose Files</strong>
		<span class="mrgn-tp-sm"></span>
	</label>
</div>

<!-- For single file inputs -->
<label for="file" class="required"><span class="field-name">File</span></label>
<div class="form-group form-sm">
	<input id="file" class="file-control file-control-1" name="files" type="file" data-rule-extension="pdf">
	<label for="file">
		<strong class="btn btn-md btn-default">Choose File</strong>
		<span class="mrgn-tp-sm"></span>
	</label>
</div>
```
CSS:
```css
/*
	By Osvaldas Valutis, www.osvaldas.info
	Available for use under the MIT License
	
	Modified by Kody Duncan, www.cybersubtye.ca
*/

.js .file-control {
	height: 0.1px;
	opacity: 0;
	overflow: hidden;
	position: absolute;
	width: 0.1px;
	z-index: -1;
}

.file-control+label {
	cursor: pointer;
	display: inline-block;
	font-size: 1.25rem;
	font-weight: 700;
	max-width: 80%;
	overflow: hidden;
	padding: 0.625rem 1.25rem;
	text-overflow: ellipsis;
	white-space: nowrap;
}

.no-js .file-control+label {
	display: none;
}

.file-control:focus+label,.file-control.has-focus+label {
	outline: 1px dotted #000;
	outline: -webkit-focus-ring-color auto 5px;
}

.file-control+label * { 
/* pointer-events: none; */
/* in case of FastClick use */
}

.file-control+label svg {
	fill: currentColor;
	height: 1em;
	margin-right: 0.25em;
	margin-top: -0.25em;
	vertical-align: middle;
	width: 1em;
}

.file-control-1+label {
	color: #000;
}

.file-control-1+label {
	background-color: #fff;
	border: 1px solid #ccc;
	border-radius: 4px;
	box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    padding: 5px 5px;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
	-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
}

.file-control-1:focus+label,.file-control-1.has-focus+label {
	border-color: #66afe9;
	box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075), 0 0 8px
		rgba(102, 175, 233, .6);
	outline: 0;
	-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075), 0 0 8px
		rgba(102, 175, 233, .6);
}

.file-control-1+label span,.file-control-1+label strong {
	padding: 0.5rem 1rem;
}

.file-control-1+label span {
    display: inline-block;
    height: 25px;
    overflow: hidden;
    text-overflow: ellipsis;
    vertical-align: top;
    white-space: nowrap;
    width: 100%;
}

.file-control-1+label span div {
    height: 45px;
    overflow-y: hidden;
    overflow-x: auto;
	width: 95%;
}

.file-control-1+label strong.error {
	display: none !important;
}

@media screen and (max-width: 50em) {
	.file-control-1+label strong {
		display: block;
	}
}
```
As for the [JavaScript](http://tympanus.net/Tutorials/CustomFileInputs/js/custom-file-input.js). This isn't all my code I just modified the CSS to work with wet.

Results:
![file-input-multiple-1](https://cloud.githubusercontent.com/assets/22446865/19491724/685f2a82-954a-11e6-819e-efa6ad2350af.png)
![file-input-multiple-2](https://cloud.githubusercontent.com/assets/22446865/19491792/a5ed8ec0-954a-11e6-8413-d44806a480c8.png)
