### ISSUE TITLE
SCSS variables: Overlay Plugin questions

### ISSUE THREAD

**Issue by melodyma** [wet-boew/wet-boew#6550]
@LaurentGoderre - For overlay, this is what I propose as the parameters we should extract as variables. My notes are proceeded by  `//***` in the code snippets below. Things I think should be customizable are labelled as `//*** CUSTOMIZE` along with some inline questions and notes.

overlay/_base.scss
```scss
.wb-overlay {
	background-clip: border-box;
	background-color: #fff; //*** CUSTOMIZE - Question: This colour is also inherited by the modal overlay background, but I think people may want to customize the side overlay vs. modal overlay backgrounds since side overlays are usually used for off-canvas navs vs. modals that are strictly modals.
	border: 0;
	border-radius: 0;
	display: none;
	// Push the element onto the GPU stack
	transform: translateZ(0);
	z-index: 1050;

	&.wb-inview {
		display: block;
	}

	&.open {
		display: inline-block;
		position: fixed;
	}
}

%overlay-panel {
	height: 100%;
	max-width: 90%;  //*** CUSTOMIZE 
	top: 0;
}

%overlay-bar {
	border-bottom: 0;
	left: 0;
	max-height: 90%;  //*** CUSTOMIZE 
	min-width: 100%;
}

%overlay-popup {
	max-height: 90%;  //*** CUSTOMIZE 
	max-width: 90%;  //*** CUSTOMIZE 
}

/*
 *	Overlay styles
 */
.wb-panel-l {
	@extend %overlay-panel;
	left: 0;
}

.wb-panel-r {
	@extend %overlay-panel;
	right: 0;
}

.wb-bar-t {
	@extend %overlay-bar;
	top: 0;
}

.wb-bar-b {
	@extend %overlay-bar;
	bottom: 0;
}

.wb-popup-mid {
	@extend %overlay-popup;
	border-radius: 6px;
	bottom: 0;
	left: 0;
	margin: auto;
	right: 0;
	top: 0;
}

.wb-popup-full {
	height: 100%;
	left: 0;
	top: 0;
	width: 100%;
}

/*
 *	Overlay parts
 */
.overlay-def {
	overflow-y: auto;

	header {
		background-color: #000; //*** CURRENTLY NOT USED
		color: #fff;  //*** CUSTOMIZE 
		display: block;
		padding: 0 44px 0 1em;  //*** CUSTOMIZE 
	}

	.modal-title {
		font-size: 1.15em;  //*** CUSTOMIZE 
		padding: 10px 0;  //*** CUSTOMIZE 
	}

	&.wb-bar-t,
	&.wb-bar-b {
		background-color: #000; //*** Why is this not themed like the left and right side overlays?
	}

	.mfp-close {
		color: #fff;  //*** CUSTOMIZE 
	}
}

.hidden-hd {
	.modal-body {
		padding-top: 50px;
	}

	.overlay-close {
		background-color: #000;  //*** CUSTOMIZE 
		border-radius: 999px; //*** CHANGE TO 50%
		height: 1em;  //*** CUSTOMIZE 
		line-height: 1em;
		margin-right: 20px;
		margin-top: 10px;
		width: 1em;  //*** CUSTOMIZE 
	}
}

[dir=rtl] {
	.mfp-close {
		left: 0;
		right: auto;
	}

	.wb-panel-l {
		left: auto;
		right: 0;
	}

	.wb-panel-r {
		left: 0;
		right: auto;
	}

	.overlay-def {
		header {
			padding: 0 1em 0 44px;
		}
	}
}
```

overlay/_ie8.scss
Should `1px solid #999;` be the scss placeholder and extended by left, right, top and bottom? 
```scss
%overlay-ie8-border-left-999 {
	border-left: 1px solid #999; //*** CUSTOMIZE
}

%overlay-ie8-border-right-999 {
	border-right: 1px solid #999; //*** CUSTOMIZE
}

.lt-ie9 {
	.wb-panel-l {
		@extend %overlay-ie8-border-right-999;
	}

	.wb-panel-r {
		@extend %overlay-ie8-border-left-999;
	}

	.wb-bar-t {
		border-bottom: 1px solid #999; //*** CUSTOMIZE
	}

	.wb-bar-b {
		border-top: 1px solid #999; //*** CUSTOMIZE
	}

	&[dir=rtl] {
		.wb-panel-l {
			@extend %overlay-ie8-border-left-999;
			border-right: 0;
		}

		.wb-panel-r {
			@extend %overlay-ie8-border-right-999;
			border-left: 0;
		}
	}
}
```
