### ISSUE TITLE
Tabbed Interface: print content tab by tab 

### ISSUE THREAD

**Issue by sophiek4905** [wet-boew/wet-boew#6883]
Since we have long table for each tab, it is possible to print content from the active tab only ?

**Comment by pjackson28** [comment]
@sophiek4905 You could use CSS to do that, although we generally recommend against hiding content on print. Something like the following would work:
```css
@media print {
	.wb-tabs [role="tabpanel"][aria-hidden="true"], .wb-tabs summary[aria-expanded="false"] + .tgl-panel {
		display: none !important;
	}
}
```
