### ISSUE TITLE
Form validation: Increasing text size

### ISSUE THREAD

**Issue by sarasuri** [wet-boew/wet-boew#6910]
On the form validation demo page, when you change the text size in Firefox v38 using Firefox Zoom Text Only (at 200%) some letters in the input box are cut off. Also, the submit and reset buttons labels are cut off at the bottom.

For example,
![screenshot](https://cloud.githubusercontent.com/assets/12256067/8439930/160b60cc-1f3d-11e5-92f9-57b4071e614e.gif)

**Comment by pjackson28** [comment]
It seems to come from the following CSS from Bootstrap:
```css
input[type="reset"], input[type="button"], input[type="submit"] {
    height: 37px;
}
```
It isn't an issue with the regular zoom but the height doesn't scale with text-only zoom.

@thomasgohard Thoughts on this?
