### ISSUE TITLE
Tabbed Interface: Top Selection Bar not correct when multiple lines on Tab

### ISSUE THREAD

**Issue by RitchieD** [wet-boew/wet-boew#7001]
WET 4.0.16  (IE 11)
When you have several tabs and some tabs are 2+ words causing multiple lines, then the selected tab as small issue.  The top grey focus bar shows in the middle of the tab instead of the top.

````
<div class="wb-tabs">
        <div class="tabpanels">
            <details id="details-panel1">
                <summary>Cars</summary>
                <p>
                    ...
                </p>
            </details>
            <details id="details-panel2" open="open">
                <summary>Trucks</summary>
                <p>
                    ...
                </p>
            </details>
            <details id="details-panel3" open="open">
                <summary>Bananas</summary>
                <p>
                    ...
                </p>
            </details>
            <details id="details-panel4" open="open">
                <summary>Blue Shoes</summary>
                <p>
                    ...
                </p>
            </details>
            <details id="details-panel5" open="open">
                <summary>Blue Skies</summary>
                <p>
                    ...
                </p>
            </details>
            <details id="details-panel6" open="open">
                <summary>Elephants</summary>
                <p>
                    ...
                </p>
            </details>
            <details id="details-panel7" open="open">
                <summary>Hippopotamus</summary>
                <p>
                    ...
                </p>
            </details>
        </div>
    </div>
````

**Comment by pjackson28** [comment]
@thomasgohard Please look into this. This is likely related to the fix that enabled tabs to wrap within the tab itself.

**Comment by hsrudnicki** [comment]
@thomasgohard and others: Can be this issue closed? Please update this issue's status, thx

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue as resolved or if otherwise?
Either way, please update this issue's status, thank you

**Comment by RitchieD** [comment]
So....is it going to be fixed or what?

**Comment by hsrudnicki** [comment]
@thomasgohard @pjackson28 : one of you or both please respond to the above / update this issue's status! Thank you

**Comment by hsrudnicki** [comment]
Is this still an issue for the current year or otherwise?

**Comment by kodecount** [comment]
@masterbee This appears to be fixed in latest WET.

**Comment by RitchieD** [comment]
I downloaded the latest version of WT 4.0.23.  Issues still exists.

**Comment by MaximMartel** [comment]
i was able to reproduce this issue with 4.0.23, on IE 11 and FF. Looking into providing you with a fix.

**Comment by kodecount** [comment]
@MaximMartel My suggestion would be to use the `<li>` instead `<a>` for the top border when active.

**Comment by MaximMartel** [comment]
Thanks @kodecount ! your help is greatly appreciated.

**Comment by RobJohnston** [comment]
I still see this as a problem in 4.0.27.  Here's the CSS to make the override mentioned by @thekodester  until a fix is done (improvements welcome):
```css
    <style type="text/css">
        .wb-tabs [role=tablist] > li {
            vertical-align: middle;
        }
        .wb-tabs [role=tablist] > li.active {
            border-top-color: #666;
            border-style: solid;
            border-width: 4px 1px 0 1px; 
        }
        .wb-tabs [role=tablist] > li.active a {
            border:none;
        }
    </style>
```
