### ISSUE TITLE
Details dropdown arrow faces left on RTL pages (even in LTR container div).

### ISSUE THREAD

**Issue by aaornrylow** [wet-boew/wet-boew#7358]
Hi,

I'm preparing an Arabic page wherein each Arabic section is followed by a details element containing the English translation for that section. I've wrapped the English translations in a container div with dir="LTR". Unfortunately that doesn't override the **.no-details[dir=rtl] details>summary:before** CSS, as the arrow still faces to the left (except in Chrome):
![capture](https://cloud.githubusercontent.com/assets/5074169/12629051/0addd4be-c514-11e5-989f-63bfa3fd027a.JPG)

Can you please recommend a way around this?

Thanks,
-Aaron

**Comment by LaurentGoderre** [comment]
This is an edge case so you might have to do some custom css like the following

```css
.no-details[dir=rtl] *[dir=ltr] details>summary:before {
   content: "\25BA\a0";
}

.no-details[dir=rtl] *[dir=ltr] details[open]>summary:before {
   content: "\25BC\a0";
}
```
