### ISSUE TITLE
Lightbox header colour is incorrect in intranet theme

### ISSUE THREAD

**Issue by sbrioux** [wet-boew/wet-boew#7512]
So I'm trying to use the intranet theme for a page I am working on and it seems like maybe the css for the modal title is incorrect.
```css
.overlay-def header {
    background-color: #000;
    color: #fff;
    display: block;
    padding: 0 44px 0 1em;
}
```

Which isn't consistent with http://wet-boew.github.io/v4.0-ci/demos/lightbox/lightbox-en.html an inline example.

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this, whether this can be closed or otherwise, thank you

**Comment by sbrioux** [comment]
Unless the header colour is supposed to be black then it's still an issue.

**Comment by hsrudnicki** [comment]
Based on the above, this started from using _white_ header text color for _black_ background-color, as well the header text color can/shall be changed to _black_ in case of _white_ background-color, therefore, again does this remain still an issue?  Can be this closed? Please update the status of this again, thank you

**Comment by sbrioux** [comment]
You are correct that the current behaviour is black background with white text in the header.  However, like I stated it is not consistent with the rest of the templates where it is a blue background with white text.  Are you saying that the templates will be changing to a black background?

Current fix I have put in for pages using the lightbox with the intranet template is the following:
```css
.overlay-def header {
    background: #2e5274
}
```
