### ISSUE TITLE
Overlay print issue

### ISSUE THREAD

**Issue by biljanap** [wet-boew/wet-boew#7615]
The content of overlay prints on top of the page content rendering both unreadable. This is the case with all types of overlays except Centred popup lightbox that is placed at the start of the page when printed.
It seams that WET4 removes all backgrounds for the print. Is it possible to keep background at least for full screen overlays? And maybe not even print the rest of the page?
Maybe exclude Left-panel, Right-panel, Top bar and Bottom bar from print all together like it's done for main nav, footer and search? Just a suggestion. 
It would be ideal for my current project if we would be able to print just the content of the full screen overlay and ignore the rest of the page. Any suggestions?

**Comment by kpduncan** [comment]
Suggestion would be to have a web page which is just a modal and change the buttons of the modal to redirect to the desired page.

**Comment by kodecount** [comment]
@biljanap Do you mean when print the page? If so I don't believe their is any print support with overlays?

@masterbee @duboisp Do you know if overlays have print support? I tired printing a page while overlay active and it did as described here. The overlay text was over top the of the content under the overlay.

**Comment by biljanap** [comment]
@kodecount yes, it's when printing the page.

**Comment by kodecount** [comment]
@duboisp @LaurentGoderre What about adding css like:

```css
@media print {
.modal-content {
display: block !important;
}
.modal-content.open {
display: none !important;
}
.modal-content.no-print {
display: none !important;
}
}
```
