### ISSUE TITLE
horizontal lines in financial tables

### ISSUE THREAD

**Issue by thai-po** [wet-boew/wet-boew#7678]
I need to add horizontal lines into financial tables to represent totals.

We are currently using `<hr>` tags, which isn't semantically correct, but it validates.
You can see an example here: www.fin.gc.ca/pub/qfr-rft/qfr-rft-2015-16-qt3-eng.asp#_Toc361232168

When I add the `<hr>` tag to WET4, the border colour (#eee) doesn't have enough of a contrast. Can you add the following CSS style:

> table hr {
> 	border-top: 1px solid black;
> }

or something similar?

**Comment by cybersubtype** [comment]
Why not do something like this:

```html
<tr>
<td></td>
<td colspan="6" style="background: black;"></td>
</tr>
```
![demo](https://cloud.githubusercontent.com/assets/22446865/18951374/461fcb7c-861b-11e6-8c46-1499aeeab254.png)

**Comment by thai-po** [comment]
That works, but to reduce the height I would have to change all the `<td>`'s in that `<tr>`.

**Comment by cybersubtype** [comment]
What about using css child? Like this:

HTML:
```html
<tr class="r4">
<td></td>
<td colspan="6"></td>
</tr>
```

CSS:
```css
#mainContent table .r4 {
	background-color: #fff;
}

.r4 td:nth-child(2) {
	background-color: #000;
}
```

**Comment by thai-po** [comment]
Oh I really like that idea! 

I modified your code a bit to fit our multiple use cases.

Can we implement this:
HTML:

```html
<table class="table table-striped table-bordered text-right">
...
    <tr class="line skip1">
        <td>&nbsp;</td>
        <td colspan="3">&nbsp;</td>
        <td colspan="3">&nbsp;</td>
    </tr>
...
</table>
```

CSS:
```css
.line td {
    padding: 0px 6px !important;
    font-size: 2px;
}

.line.skip1 td:nth-child(n+2),
.line.skip2 td:nth-child(n+3),
.line.skip3 td:nth-child(n+4) {
    background-color: #000;
    background-clip: content-box;
}
```

**Comment by cybersubtype** [comment]
Hey did this work? I never seen `nth-child(n+2)` so just curious?

**Comment by cybersubtype** [comment]
Glad to hear that. Figured out my own question.

**Comment by thai-po** [comment]
I'm glad you learned something new :) And thanks for your help!
Can you or someone commit this? I just started contributing so I'm not really sure how it works.

**Comment by cybersubtype** [comment]
@thai-po I can probably start a PR in the future. I'm getting introduced to how it works next week.

**Comment by duboisp** [comment]
@kodecount before to send a PR for that kind of table, a financial table, take a look at the zebra plugin and how it handle and style complex table. 

It could better to take advantage of using multiple row group ```<tbody>``` and adjust the row group intersection CSS to be more defined instead of creating an additional and specific CSS class.

Here some interesting reading about row group techniques:
* http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/tableparser/rowgrouping-techniques.html
* http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/tableparser/summariesrowgroup-techniques.html
* http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/tableparser/headerrowgroupstructure-techniques.html

Cheers

**Comment by LaurentGoderre** [comment]
:+1: on using `tbody` and CSS to acheive this. using empty row in data tables is not ideal

**Comment by kodecount** [comment]
@duboisp Nice concept, but the links don't work in Chrome and are a outdated version of WET. Why wasn't this updated and kept alive with feature WET production?

**Comment by duboisp** [comment]
@kodecount The links work in chrome for me. The [documentation](http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/tableparser/index-en.html) are in an outdated version of WET because it should belong to the wet style guide and it wasn't moved neither reviewed because of a lack of resource.

**Comment by kodecount** [comment]
@duboisp Weird my default zoom changed to 90% and that was the issue.

**Comment by thai-po** [comment]
I agree with @LaurentGoderre; we should avoid empty rows, but I'm not sure how to style it without  one.

This is an example of one of my tables: 
![screen shot 2016-10-26 at 1 35 00 pm](https://cloud.githubusercontent.com/assets/1847090/19737353/194bb5e0-9b81-11e6-85e7-456c0c1d0b20.png)
[SRC: www.fin.gc.ca/pub/qfr-rft/qfr-rft-2015-16-qt3-eng.asp#_Toc361232168]

The line needs to span across 3 columns to represent the 2015-2016 and the 2014-2015 years and it needs the gap in-between.

**Comment by kodecount** [comment]
The links @duboisp provide he used this code:

```css
.wet-boew-zebra tbody.table-rowgroupmarker, .wet-boew-zebra tfoot.table-rowgroupmarker {
border-top: solid black 2px;
}
```
