### ISSUE TITLE
Tables:  separated column header row results in 2 tables when it should only be 1 single table.

### ISSUE THREAD

**Issue by SBleeks** [wet-boew/wet-boew#7707]
When we use any options that modify scrolling in the table (ScrollX or ScrollY) the initialization process will split the table in two, one for the header, one for the body. This is required when the user wants to scroll the body content without having the header disappear. It is entirely controlled by the jQuery DataTable API.
This means that for AT users, there will be 2 tables listed when it should be 1 single table.

**Comment by LaurentGoderre** [comment]
Should we discourage the use of that featured then?

**Comment by kodecount** [comment]
From my google search of 'datatable scolling and bootstrap' I've come to the conclusion that the scrollX and scrollY feature is buggy. You could report the issue with DataTables group. Their is a neat work around that I got working:

CSS:
```css
        div.dataTables_wrapper {
            height: 800px;
            width: 800px;
            margin: 0 auto;
            /* vertical */
            overflow-y: scroll; 
            /* horizontal */
            overflow-x: scroll;
        }
```

JavaScript:
```javascript
$(window).resize(function() {
  $('.dataTables_scrollBody').css('height', ($(window).height() - 200));
  $('.dataTables_scrollBody').css('width', ($(window).width() - 200));
});
```
