### ISSUE TITLE
Legend tag Float:left

### ISSUE THREAD

**Issue by StdGit** [wet-boew/wet-boew#7766]
@thomasgohard

Is there a special reason why tag Legend is floating left ?

legend { 
   border-bottom: 0; 
  **float: left;**
 } 

If you add a tag like fieldset after it, it will be right aligned

https://github.com/wet-boew/wet-boew/commit/42a76b1bffa30b3103542892b23f4cbf6ca5d14a

https://github.com/wet-boew/wet-boew/blob/a5b906efd6b5cc2d74167d53da9bbe02b4150b11/src/base/bootstrap-overrides/_base.scss#L601

**Comment by kodecount** [comment]
It because [Line 609](https://github.com/wet-boew/wet-boew/blob/a5b906efd6b5cc2d74167d53da9bbe02b4150b11/src/base/bootstrap-overrides/_base.scss#L609) doesn't work other wise.

**Comment by kodecount** [comment]
What about using:

```css
legend {
  margin-bottom: 0;
}

legend:after {
    border-bottom: 1px solid #e5e5e5;
    content: "";
    display: block;
}
```
This well create a border under the legend title if we really need the border?
