### ISSUE TITLE
Question about table column headers read out with TDs - custom

### ISSUE THREAD

**Issue by alanfluff** [wet-boew/wet-boew#9273]
Hi,

Re:

https://wet-boew.github.io/v4.0-ci/demos/tables/tables-en.html#wb-auto-1

I am attempting to **accessibly** enable the pagination on a GOC web page that *currently* only uses the straight datatables plugin, not WET, so apologies up front for not asking a WET-only question.

When using AT, e.g. NVDA, I am trying to discover how the WET implementation of datatables pagination results in the associated TH being read out with the TD when the next page of results  is displayed.

It seems the default datatables use of pagination does not alert the audio AT user to the new "page" of rows displayed in the table at all.

Adding `aria-live polite` and `aria-atomic true` to a `table` I do hear the row of `th`s read out, once, then all the `td`s, however I do not hear each `td` introduced by the text in its associated `th`.

I have looked at the *Basic Example* implementation here and cannot see how WET is achieving this.

I either want to learn how I can do this, or implement the WET sortable, paginated table,

Sorry for being so vague, is this something you can comment on?

Thanks in advance for any pointers. Cheers, Alan

**Comment by alanfluff** [comment]
Thank you very much @kodz1, it's a weird one (the WET implementation reading the table on pagination change and the original plugin on Datatables apparently not doing this). It seems a highly valuable behaviour. So thank you again for helping me get closer to solving this.

I will close this when I solve it, I understand a mod may need to close it sooner, though it would be nice if it stayed open until I can find and post the answer : )

**Comment by kodz1** [comment]
Yes, I personally have tried looking into other javascript tables, but datatables provides some of the best features, but lacks a lot of accessibility.

When datatables put their primary focus into their paid tier offering assistance on improving this is now fruitless I found.

###### I am just a volunteer on this GitHub project.

**Comment by alanfluff** [comment]
Thank you @kodz1 - I am increasingly thinking I should just jump ship from vanilla Datatables to WET Datatables.

I'll go try this again; the first hacked attempt I quickly tried failed and I couldn't -- on first inspection -- work out why. So I'll go try harder and either post what error I made and how I solved it (for anyone else reading this like me), or, ask as short and specific a question as I can, in case you/colleagues might see what I am missing.

**Comment by alanfluff** [comment]
@kodz1 Very happy here - I have the basic WET variant table in and working; e.g.

- on pagination change the `table` contents is read out correctly - brilliant
- the pagination is block-level and each may be navigated to with arrow-key navigation

Both these (and perhaps other) a11y issues appeared when I enabled pagination with the (none the less brilliant) Vanilla Datatables. Thank you.

One question if I may prevail upon your time again (thank you in advance if you get a change to reply):

Please can you tell me if there is a page that documents the official steps for adding the correct/sufficiently complete dependencies to allow a plugin such as WET Datatables to operate correctly, in Fr as well as En (etc)?

The reason I ask is that this is my journey to this point:

1. we don't (yet) use WET
2. I tried in the past to hack in an individual piece of WET, e.g. this `table` plugin and failed (I ensured what I thought were the needed JS and CSS (clearly I missed stuff))
3. this time I hacked again and noted 404s resulting from (presumably ) when `wet-boew.min.js` loaded and looked around for additional files, specifically: `wet-boew.min.js.map`, `i18n/en.min.js`, and `deps/jquery.dataTables.min.js`
4. so I hand-added these files/folders and the raw unstyled `table`, as noted, worked
5. *but*, I am certain I am not following the correct steps for adding a single WET plugin (as opposed to the wholesale adoption of the WET template)

Thanks in advance for any comment.

**Comment by duboisp** [comment]
@alanfluff with a few modification, it is possible to make the datatable modular.

After the data table library is loaded and your have initialized the datatable, see bellow the event handler we aer using in WET to enhance the pagination and the sorting button.

The pagination and the sorting button are mostly managed by the following code.
```javascript

// Handle the draw.dt event
$document.on( "draw.dt", selector, function( event, settings ) {
	var $elm = $( event.target ),
		pagination = $elm.next( ".bottom" ).find( "div:first-child" ),
		paginate_buttons = $elm.next( ".bottom" ).find( ".paginate_button" ),
		pbLength = paginate_buttons.length,
		pHasLF = pagination.find( ".last, .first" ).length === 2,
		pHasPN = pagination.find( ".previous, .next" ).length === 2,
		ol = document.createElement( "OL" ),
		li = document.createElement( "LI" );

	// Handle sorting/ordering
	var order = $elm.dataTable( { "retrieve": true } ).api().order();
	$elm.find( "th" ).each( function( index ) {
		var $th = $( this ),
			$btn = $th.find( "button" );
		if ( order && order[ 0 ][ 0 ] === index ) {
			var label = ( order[ 0 ][ 1 ] === "desc" ) ? i18nText.aria.sortAscending : i18nText.aria.sortDescending;
			label = $btn.text() + label;
			$btn.attr( "title", label );
		}
		$th.removeAttr( "aria-label" );
	} );

	// Determine if Pagination required
	if (
		pbLength === 1 ||
		(
			pbLength === 3 &&
			(
				pHasLF ||
				pHasPN
			)
		) ||
		(
			pbLength === 5 &&
			pHasLF &&
			pHasPN
		)
	) {
		pagination.addClass( "hidden" );
	} else {

		// Make sure Pagination is visible
		pagination.removeClass( "hidden" );

		// Update Pagination List
		for ( var i = 0; i < paginate_buttons.length; i++ ) {
			var item = li.cloneNode( true );
			item.appendChild( paginate_buttons[ i ] );
			ol.appendChild( item );
		}

		ol.className = "pagination mrgn-tp-0 mrgn-bttm-0";
		pagination.empty();
		pagination.append( ol );

		// Update the aria-pressed properties on the pagination buttons
		// Should be pushed upstream to DataTables
		$elm.next( ".bottom" ).find( ".paginate_button" )
			.attr( {
				"href": "#" + $elm.get( 0 ).id
			} )

			// This is required to override the datatable.js (v1.10.13) behavior to cancel the event propagation on anchor element.
			.on( "keypress", function( evn ) {
				if ( evn.keyCode === 13 ) {
					window.location = evn.target.href;
				}
			} )

			.not( ".previous, .next" )
			.attr( "aria-pressed", "false" )
			.html( function( index, oldHtml ) {
				return "<span class='wb-inv'>" + i18nText.paginate.page + " </span>" + oldHtml;
			} )
			.filter( ".current" )
			.attr( "aria-pressed", "true" );
	}

	// Identify that the table has been updated
	$elm.trigger( "wb-updated" + selector, [ settings ] );
} );

// Identify that initialization has completed
$document.on( "init.dt", function( event ) {
	var $elm = $( event.target ),
		settings = $.extend( true, {}, defaults, window[ componentName ], wb.getData( $elm, componentName ) );

	// Handle sorting/ordering
	var ordering = ( settings && settings.ordering === false ) ? false : true;
	if ( ordering ) {
		$elm.find( "th" ).each( function() {
			var $th = $( this ),
				label = ( $th.attr( "aria-sort" ) === "ascending" ) ? i18nText.aria.sortDescending : i18nText.aria.sortAscending;

			$th.html( "<button type='button' aria-controls='" + $th.attr( "aria-controls" ) +  "' title='" + $th.text().replace( /'/g, "&#39;" ) + label + "'>" + $th.html() + "<span class='sorting-cnt'><span class='sorting-icons' aria-hidden='true'></span></span></button>" );
			$th.removeAttr( "aria-label tabindex aria-controls" );
		} );
		$elm.attr( "aria-label", i18nText.tblFilterInstruction );
	}
	wb.ready( $( event.target ), componentName );
} );
```
The changes require is :
* Remove the reference to `wb.` object
* Change the `$document.on` for `$( document.body ).on`
* Create your own i18Text object


For your custom i18Text object, it will be structured like this:
```javascript
let i18nText = {
					aria: {
						sortAscending: i18n( "sortAsc" ),
						sortDescending: i18n( "sortDesc" )
					},
					emptyTable: i18n( "emptyTbl" ),
					info: i18n( "infoEntr" ),
					infoEmpty: i18n( "infoEmpty" ),
					infoFiltered: i18n( "infoFilt" ),
					lengthMenu: i18n( "lenMenu" ),
					loadingRecords: i18n( "load" ),
					paginate: {
						first: i18n( "first" ),
						last: i18n( "last" ),
						next: i18n( "nxt" ),
						previous: i18n( "prv" ),
						page: i18n( "page" )
					},
					processing: i18n( "process" ),
					search: i18n( "filter" ),
					thousands: i18n( "info1000" ),
					zeroRecords: i18n( "infoEmpty" ),
					tblFilterInstruction: i18n( "tbFilterInst" )
				};
```
and you will find the corresponding text replacement value in our big [CSV file](https://github.com/wet-boew/wet-boew/blob/master/src/i18n/i18n.csv) or via those JS compiled file:
* English: https://github.com/wet-boew/wet-boew-dist/blob/v4.0-dist/wet-boew/js/i18n/en.js
* French: https://github.com/wet-boew/wet-boew-dist/blob/v4.0-dist/wet-boew/js/i18n/fr.js


Finally, here the CSS. I extracted it from the compiled css available here: https://github.com/wet-boew/wet-boew-dist/blob/v4.0-dist/theme-wet-boew/css/theme.css 
You might need to clean it up a little.
```css
.pagination.disabled,
.pager.disabled, .pagination > li.disabled,
.pager > li.disabled, [dir=rtl] .pagination [rel="prev"]:before,
[dir=rtl] .pager [rel="prev"]:before, [dir=rtl] .pagination [rel="next"]:after,
[dir=rtl] .pager [rel="next"]:after, #wb-bc li:first-child:before, [dir=rtl] #wb-bc li:first-child:before, #mb-pnl .modal-body h2, table.dataTable thead .sorting-icons, table.dataTable thead .sorting_asc_disabled .sorting-icons:before, table.dataTable thead .sorting_desc_disabled .sorting-icons:after, .dataTables_wrapper .dataTables_paginate .paginate_button.disabled, [dir=rtl] .dataTables_wrapper .dataTables_paginate .paginate_button.previous:before, [dir=rtl] .dataTables_wrapper .dataTables_paginate .paginate_button.next:after, [dir=rtl] .dataTables_wrapper .dataTables_paginate .paginate_button.disabled, .wb-tabs.carousel-s1 [role="tablist"] > li, .wb-tabs.carousel-s2 [role="tablist"] > li {
  display: none; }
.pagination > li:first-child [rel="prev"]:before,
.pager > li:first-child [rel="prev"]:before, [dir=rtl] .pagination [rel="next"]:before,
[dir=rtl] .pager [rel="next"]:before, .dataTables_wrapper .dataTables_paginate .paginate_button.previous:before, [dir=rtl] .dataTables_wrapper .dataTables_paginate .paginate_button.next:before, .pagination > li:last-child [rel="next"]:after,
.pager > li:last-child [rel="next"]:after, [dir=rtl] .pagination [rel="prev"]:after,
[dir=rtl] .pager [rel="prev"]:after, .dataTables_wrapper .dataTables_paginate .paginate_button.next:after, [dir=rtl] .dataTables_wrapper .dataTables_paginate .paginate_button.previous:after, table.dataTable thead .sorting-icons:before, table.dataTable thead .sorting-icons:after {
  content: " ";
  font-family: "Glyphicons Halflings";
  font-weight: 400;
  line-height: 1em;
  position: relative;
  top: .1em; }

.pagination > li:first-child [rel="prev"]:before,
.pager > li:first-child [rel="prev"]:before, [dir=rtl] .pagination [rel="next"]:before,
[dir=rtl] .pager [rel="next"]:before, .dataTables_wrapper .dataTables_paginate .paginate_button.previous:before, [dir=rtl] .dataTables_wrapper .dataTables_paginate .paginate_button.next:before {
  content: "\e091";
  margin-right: .5em; }

.pagination > li:last-child [rel="next"]:after,
.pager > li:last-child [rel="next"]:after, [dir=rtl] .pagination [rel="prev"]:after,
[dir=rtl] .pager [rel="prev"]:after, .dataTables_wrapper .dataTables_paginate .paginate_button.next:after, [dir=rtl] .dataTables_wrapper .dataTables_paginate .paginate_button.previous:after {
  content: "\e092";
  margin-left: .5em; }

/*
 * Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
 * wet-boew.github.io/wet-boew/License-eng.html / wet-boew.github.io/wet-boew/Licence-fra.html
 */
table.dataTable, .dataTables_wrapper .dataTables_scroll {
  clear: both; }

table.dataTable thead th:active, table.dataTable thead td:active {
  outline: none; }

.dataTables_wrapper .dataTables_filter, .dataTables_wrapper .dataTables_length {
  font-weight: 400; }

table.dataTable thead th, table.dataTable tfoot th {
  font-weight: 700; }

table.dataTable thead th, table.dataTable thead td, table.dataTable tfoot th, table.dataTable tfoot td, table.dataTable.no-footer, .dataTables_wrapper.no-footer .dataTables_scrollBody {
  border-bottom: 1px solid #111; }

table.dataTable th.right, table.dataTable td.right {
  text-align: right; }

table.dataTable th.center, table.dataTable td.center, table.dataTable td.dataTables_empty {
  text-align: center; }

table.dataTable.rowborder tbody th,
table.dataTable.rowborder tbody td, table.dataTable.display tbody th,
table.dataTable.display tbody td {
  border-top: 1px solid #ddd; }

table.dataTable.rowborder tbody tr:first-child th,
table.dataTable.rowborder tbody tr:first-child td, table.dataTable.display tbody tr:first-child th,
table.dataTable.display tbody tr:first-child td, table.dataTable.cell-border tbody tr:first-child th,
table.dataTable.cell-border tbody tr:first-child td {
  border-top: 0; }

table.dataTable.cell-border tbody th,
table.dataTable.cell-border tbody td {
  border-right: 1px solid #ddd;
  border-top: 1px solid #ddd; }

table.dataTable.cell-border tbody tr th:first-child,
table.dataTable.cell-border tbody tr td:first-child {
  border-left: 1px solid #ddd; }

.dataTables_wrapper .dataTables_filter, .dataTables_wrapper .dataTables_length, .dataTables_wrapper .dataTables_info, .dataTables_wrapper .dataTables_processing {
  color: #333; }

table.dataTable.display tbody tr:hover.selected > .sorting_1, table.dataTable.display tbody tr.odd:hover.selected > .sorting_1, table.dataTable.display tbody tr.even:hover.selected > .sorting_1, table.dataTable.order-column.hover tbody tr:hover.selected > .sorting_1, table.dataTable.order-column.hover tbody tr.odd:hover.selected > .sorting_1, table.dataTable.order-column.hover tbody tr.even:hover.selected > .sorting_1 {
  background-color: #a1aec7; }

table.dataTable.display tbody tr:hover.selected > .sorting_2, table.dataTable.display tbody tr.odd:hover.selected > .sorting_2, table.dataTable.display tbody tr.even:hover.selected > .sorting_2, table.dataTable.order-column.hover tbody tr:hover.selected > .sorting_2, table.dataTable.order-column.hover tbody tr.odd:hover.selected > .sorting_2, table.dataTable.order-column.hover tbody tr.even:hover.selected > .sorting_2 {
  background-color: #a2afc8; }

table.dataTable.display tbody tr:hover.selected > .sorting_3, table.dataTable.display tbody tr.odd:hover.selected > .sorting_3, table.dataTable.display tbody tr.even:hover.selected > .sorting_3, table.dataTable.order-column.hover tbody tr:hover.selected > .sorting_3, table.dataTable.order-column.hover tbody tr.odd:hover.selected > .sorting_3, table.dataTable.order-column.hover tbody tr.even:hover.selected > .sorting_3 {
  background-color: #a4b2cb; }

table.dataTable.display tbody tr.odd.selected > .sorting_1, table.dataTable.order-column.stripe tbody tr.odd.selected > .sorting_1 {
  background-color: #a6b3cd; }

table.dataTable.display tbody tr.odd.selected > .sorting_2, table.dataTable.order-column.stripe tbody tr.odd.selected > .sorting_2 {
  background-color: #a7b5ce; }

table.dataTable.display tbody tr.odd.selected > .sorting_3, table.dataTable.order-column.stripe tbody tr.odd.selected > .sorting_3 {
  background-color: #a9b6d0; }

table.dataTable.display tbody tr.selected:hover, table.dataTable.display tbody tr.odd.selected:hover, table.dataTable.display tbody tr.even.selected:hover, table.dataTable.hover tbody tr.selected:hover, table.dataTable.hover tbody tr.odd.selected:hover, table.dataTable.hover tbody tr.even.selected:hover {
  background-color: #a9b7d1; }

table.dataTable.display tbody tr.odd.selected, table.dataTable.stripe tbody tr.odd.selected {
  background-color: #abb9d3; }

table.dataTable.display tbody tr.even.selected > .sorting_1, table.dataTable.display tbody tr.selected > .sorting_1, table.dataTable.display tbody tr.selected > .sorting_2, table.dataTable.display tbody tr.selected > .sorting_3, table.dataTable.order-column tbody tr.selected > .sorting_1, table.dataTable.order-column tbody tr.selected > .sorting_2, table.dataTable.order-column tbody tr.selected > .sorting_3, table.dataTable.order-column.stripe tbody tr.even.selected > .sorting_1 {
  background-color: #acbad4; }

table.dataTable.display tbody tr.even.selected > .sorting_2, table.dataTable.order-column.stripe tbody tr.even.selected > .sorting_2 {
  background-color: #adbbd6; }

table.dataTable.display tbody tr.even.selected > .sorting_3, table.dataTable.order-column.stripe tbody tr.even.selected > .sorting_3 {
  background-color: #afbdd8; }

table.dataTable thead .sorting_asc, table.dataTable thead .sorting_desc {
  background-color: #e7e7e7; }

table.dataTable.display tbody tr:hover > .sorting_1, table.dataTable.display tbody tr.odd:hover > .sorting_1, table.dataTable.display tbody tr.even:hover > .sorting_1, table.dataTable.order-column.hover tbody tr:hover > .sorting_1, table.dataTable.order-column.hover tbody tr.odd:hover > .sorting_1, table.dataTable.order-column.hover tbody tr.even:hover > .sorting_1 {
  background-color: #eaeaea; }

table.dataTable.display tbody tr:hover > .sorting_2, table.dataTable.display tbody tr.odd:hover > .sorting_2, table.dataTable.display tbody tr.even:hover > .sorting_2, table.dataTable.order-column.hover tbody tr:hover > .sorting_2, table.dataTable.order-column.hover tbody tr.odd:hover > .sorting_2, table.dataTable.order-column.hover tbody tr.even:hover > .sorting_2 {
  background-color: #ebebeb; }

table.dataTable.display tbody tr:hover > .sorting_3, table.dataTable.display tbody tr.odd:hover > .sorting_3, table.dataTable.display tbody tr.even:hover > .sorting_3, table.dataTable.order-column.hover tbody tr:hover > .sorting_3, table.dataTable.order-column.hover tbody tr.odd:hover > .sorting_3, table.dataTable.order-column.hover tbody tr.even:hover > .sorting_3 {
  background-color: #eee; }

table.dataTable.display tbody tr.odd > .sorting_1, table.dataTable.order-column.stripe tbody tr.odd > .sorting_1 {
  background-color: #f1f1f1; }

table.dataTable.display tbody tr.odd > .sorting_2, table.dataTable.order-column.stripe tbody tr.odd > .sorting_2 {
  background-color: #f3f3f3; }

table.dataTable.display tbody tr:hover, table.dataTable.display tbody tr.odd:hover, table.dataTable.display tbody tr.odd > .sorting_3, table.dataTable.display tbody tr.even:hover, table.dataTable.hover tbody tr:hover, table.dataTable.hover tbody tr.odd:hover, table.dataTable.hover tbody tr.even:hover, table.dataTable.order-column.stripe tbody tr.odd > .sorting_3 {
  background-color: #f5f5f5; }

table.dataTable.display tbody tr.odd, table.dataTable.display tbody tr.even > .sorting_1, table.dataTable.display tbody tr > .sorting_1, table.dataTable.display tbody tr > .sorting_2, table.dataTable.display tbody tr > .sorting_3, table.dataTable.stripe tbody tr.odd, table.dataTable.order-column tbody tr > .sorting_1, table.dataTable.order-column tbody tr > .sorting_2, table.dataTable.order-column tbody tr > .sorting_3, table.dataTable.order-column.stripe tbody tr.even > .sorting_1 {
  background-color: #f9f9f9; }

table.dataTable.display tbody tr.even > .sorting_2, table.dataTable.order-column.stripe tbody tr.even > .sorting_2 {
  background-color: #fbfbfb; }

table.dataTable.display tbody tr.even > .sorting_3, table.dataTable.order-column.stripe tbody tr.even > .sorting_3 {
  background-color: #fdfdfd; }

table.dataTable, table.dataTable th, table.dataTable td {
  -webkit-box-sizing: content-box;
          box-sizing: content-box; }

table.dataTable thead .sorting .sorting-icons:before, table.dataTable thead .sorting .sorting-icons:after, table.dataTable thead .sorting_asc .sorting-icons:after, table.dataTable thead .sorting_desc .sorting-icons:before {
  background: #fff;
  border: 1px solid #aaa;
  color: #757575; }

table.dataTable thead .sorting_asc .sorting-icons:before, table.dataTable thead .sorting_desc .sorting-icons:after {
  background: #ccc;
  border: 1px solid #111;
  color: #000; }

table.dataTable thead .sorting, table.dataTable thead .sorting_asc, table.dataTable thead .sorting_desc {
  cursor: pointer; }

table.dataTable thead .sorting .sorting-icons, table.dataTable thead .sorting_asc .sorting-icons, table.dataTable thead .sorting_desc .sorting-icons, table.dataTable thead .sorting_asc_disabled .sorting-icons, table.dataTable thead .sorting_desc_disabled .sorting-icons {
  display: inline-block; }

/*
 * Table styles
 */
table.dataTable {
  border-collapse: separate;
  border-spacing: 0;
  margin: 0 auto;
  width: 100% !important; }
  table.dataTable thead button {
    -webkit-appearance: none;
       -moz-appearance: none;
            appearance: none;
    background: transparent;
    border: 0;
    font-family: inherit;
    padding: 0;
    text-align: left; }
  table.dataTable thead .sorting-cnt {
    white-space: nowrap; }
    table.dataTable thead .sorting-cnt:before {
      content: " "; }
  table.dataTable thead .sorting-icons {
    margin-top: 2px; }
    table.dataTable thead .sorting-icons:before {
      content: "\e093";
      padding: 0 .1em 0 0; }
    table.dataTable thead .sorting-icons:after {
      content: "\e094";
      padding: 0 .04em 0 .06em; }
  table.dataTable tbody tr {
    background-color: #fff; }
    table.dataTable tbody tr.selected {
      background-color: #b0bed9; }

/*
 * Control feature layout
 */
.dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody th > div.dataTables_sizing,
.dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody td > div.dataTables_sizing {
  height: 0;
  margin: 0 !important;
  overflow: hidden;
  padding: 0 !important; }

.dataTables_wrapper .dataTables_paginate .paginate_button.previous, .dataTables_wrapper .dataTables_paginate .paginate_button.current:first-child {
  border-top-left-radius: 4px;
  border-bottom-left-radius: 4px;
  margin-left: 0; }

.dataTables_wrapper .dataTables_paginate .paginate_button.next, .dataTables_wrapper .dataTables_paginate .paginate_button.current:last-child {
  border-top-right-radius: 4px;
  border-bottom-right-radius: 4px; }

.dataTables_wrapper {
  clear: both;
  position: relative;
  zoom: 1; }
  .dataTables_wrapper .dataTables_filter {
    float: left;
    margin-right: 15px; }
    .dataTables_wrapper .dataTables_filter input {
      margin-left: .5em; }
  .dataTables_wrapper .dataTables_length {
    display: inline-block;
    margin-top: 5px; }
  .dataTables_wrapper .dataTables_info {
    display: inline-block; }
  .dataTables_wrapper .dataTables_paginate {
    padding-top: 1.25em;
    text-align: center; }
    .dataTables_wrapper .dataTables_paginate .paginate_button {
      background-color: #eaebed;
      border: 1px solid #dcdee1;
      color: #335075;
      cursor: pointer;
      display: inline-block;
      line-height: 1.4375;
      margin-bottom: .5em;
      margin-left: -1px;
      padding: 10px 16px;
      position: relative;
      text-decoration: none; }
      .dataTables_wrapper .dataTables_paginate .paginate_button.current {
        background-color: #2572b4;
        border-color: #2572b4;
        color: #fff;
        cursor: default;
        z-index: 2; }
      .dataTables_wrapper .dataTables_paginate .paginate_button:hover, .dataTables_wrapper .dataTables_paginate .paginate_button:focus, .dataTables_wrapper .dataTables_paginate .paginate_button:active {
        background-color: #d4d6da;
        border-color: #bbbfc5;
        color: #335075; }
  .dataTables_wrapper .dataTables_processing {
    background: -webkit-gradient(linear, left top, right top, from(rgba(255, 255, 255, 0)), color-stop(25%, rgba(255, 255, 255, 0.9)), color-stop(75%, rgba(255, 255, 255, 0.9)), to(rgba(255, 255, 255, 0)));
    background: linear-gradient(to right, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.9) 25%, rgba(255, 255, 255, 0.9) 75%, rgba(255, 255, 255, 0) 100%);
    background-color: #fff;
    font-size: 1.2em;
    height: 40px;
    left: 50%;
    margin-left: -50%;
    margin-top: -25px;
    padding-top: 20px;
    position: absolute;
    text-align: center;
    top: 50%;
    width: 100%; }
  .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody {
    -webkit-overflow-scrolling: touch; }
  .dataTables_wrapper.no-footer div.dataTables_scrollHead table, .dataTables_wrapper.no-footer div.dataTables_scrollBody table {
    border-bottom: 0; }
  .dataTables_wrapper:after {
    clear: both;
    content: "";
    display: block;
    height: 0;
    visibility: hidden; }

[dir=rtl] table.dataTable thead .sorting,
[dir=rtl] table.dataTable thead .sorting_asc,
[dir=rtl] table.dataTable thead .sorting_desc,
[dir=rtl] table.dataTable thead .sorting_asc_disabled,
[dir=rtl] table.dataTable thead .sorting_desc_disabled {
  text-align: right; }

[dir=rtl] table.dataTable thead .sorting:after,
[dir=rtl] table.dataTable thead .sorting_asc:after,
[dir=rtl] table.dataTable thead .sorting_desc:after,
[dir=rtl] table.dataTable thead .sorting_asc_disabled:after,
[dir=rtl] table.dataTable thead .sorting_desc_disabled:after {
  margin-left: 0;
  margin-right: 5px; }

[dir=rtl] .dataTables_wrapper .dataTables_paginate .paginate_button.previous, [dir=rtl] .dataTables_wrapper .dataTables_paginate .paginate_button.current:first-child {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
  border-top-right-radius: 4px;
  border-bottom-right-radius: 4px; }

[dir=rtl] .dataTables_wrapper .dataTables_paginate .paginate_button.next, [dir=rtl] .dataTables_wrapper .dataTables_paginate .paginate_button.current:last-child {
  border-top-left-radius: 4px;
  border-bottom-left-radius: 4px;
  border-top-right-radius: 0;
  border-bottom-right-radius: 0; }

[dir=rtl] .dataTables_wrapper .dataTables_info,
[dir=rtl] .dataTables_wrapper .dataTables_length {
  float: right; }

[dir=rtl] .dataTables_wrapper .dataTables_filter {
  float: left;
  text-align: left; }
  [dir=rtl] .dataTables_wrapper .dataTables_filter input {
    margin-left: auto;
    margin-right: .5em; }

/* Small view and under */
@media screen and (max-width: 991px) {
  /*
  WET-BOEW
  @title: Small view and under (screen only)
 */
  /*
 * Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
 * wet-boew.github.io/wet-boew/License-en.html / wet-boew.github.io/wet-boew/Licence-fr.html
 */
  .dataTables_wrapper .dataTables_info {
    padding-bottom: 5px; }
  .dataTables_wrapper .dataTables_filter {
    float: left;
    text-align: left;
    width: 100%; }
  [dir=rtl] .dataTables_wrapper .dataTables_filter {
    float: right;
    text-align: right; }
}


/* Extra-small view and over */
@media screen and (min-width: 480px) {
  /*
 * Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
 * wet-boew.github.io/wet-boew/License-en.html / wet-boew.github.io/wet-boew/Licence-fr.html
 */
  .dataTables_wrapper .dataTables_info:after {
    content: "|";
    font-size: 1.2em;
    line-height: 1em;
    padding: 0 .25em; } }


/* Extra-extra-small view */
@media screen and (max-width: 479px) {

  /*
 * Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
 * wet-boew.github.io/wet-boew/License-en.html / wet-boew.github.io/wet-boew/Licence-fr.html
 */
  .dataTables_wrapper .dataTables_length {
    width: 100%; }

}
```

Cheers
